### ISSUE TITLE
It seems like it does not work for baseUrl in tsconfig

### ISSUE THREAD

**Issue by Marcosld** [qdanik/eslint-plugin-path#10]
I have set `baseUrl` in my tsconfig. The problem is this url is converted to an absolute path by load-tsconfig package: https://github.com/egoist/load-tsconfig/blob/b288ea1f2e512b807ccbd76c3f01999a333e0124/src/index.ts#L68
After that, you are using `join` to append the tsconfig path to the expected to be relative urls defined in tsconfig:
https://github.com/qdanik/eslint-plugin-path/blob/e8f68529019e003a07c28d7f654bd50be8d6ddc6/lib/utils/config.js#L24C3-L24C3
That ends up duplicating the path to something like:
`/Users/mluis/Documents/repositories.nosync/<repo>/web/Users/mluis/Documents/repositories.nosync/<repo>/web/`

**Comment by Marcosld** [comment]
Created a quick fix PR here: https://github.com/qdanik/eslint-plugin-path/pull/11

**Comment by qdanik** [comment]
@Marcosld Version **1.2.4** now is available for install. Please, check it and let me know if everything is okay.

**Comment by Marcosld** [comment]
Neat! Working as expected now! Thanks for the quick release <3!
