### ISSUE TITLE
Enforcing all paths to be absolute (maxDepth: 0 and maxDepth: -1)

### ISSUE THREAD

**Issue by dparbhakar** [qdanik/eslint-plugin-path#14]
Hello,

On my project, I want to enforce all paths to be absolute.
When using the option `maxDepth: 0`, the relative paths that are local to the current file are still allowed.

## Using maxDepth: 0
Current Behavior:
```js
# maxDepth: 0
import { config } from "./config" # Pass
```

Example of desired behavior:
```js
# maxDepth: 0
import { config } from "./config" # Fail

# Replaced by resolved absolute path
import { config } from "@/lib/config"
```

## Using maxDepth: -1

By using `maxDepth: -1`, the desired behaviour is achieved:
```js
# maxDepth: -1
import { config } from "./config" # Fail

# Replaced by resolved absolute path
import { config } from "@/lib/config"
```

However, it breaks everything else.
The parent folder of the current file's path is added to the absolute import.

```js
# Current file path: /lib/config
# maxDepth: -1
import { config } from "@/lib/entity/validator" # Fail

# Broken result
import { config } from "@/lib/config@/lib/entity/validator" # Current file path is appended!
```

Using `maxDepth: -1` could work if it doesn't break the rest, or maybe introducing an additional flag to control this could help.

**Comment by kunaljain0212** [comment]
Were you able to find any workaround for this? @dparbhakar

**Comment by dparbhakar** [comment]
> Were you able to find any workaround for this? @dparbhakar

@kunaljain0212 Unfortunately no.

I used the plugin to transform all the paths that could be, and for the rest I simply fixed them with a Search/Replace. It is already helpful with `maxDepth: 0`, so I'm using it with that setting, and managing the rest manually.

@qdanik Were you able to reproduce this?

**Comment by qdanik** [comment]
@dparbhakar I will find a time to take a look on it in the next few days.

**Comment by kunaljain0212** [comment]
Thanks @qdanik @dparbhakar!

**Comment by qdanik** [comment]
@dparbhakar @kunaljain0212 
Guys, version is 1.4.0-beta.0 will be available soon. Please, verify changes and left feedback what I need to fix else.

**Comment by qdanik** [comment]
@dparbhakar @kunaljain0212 did you have a chance to check new rule? I still waiting for your feedback
