### ISSUE TITLE
Running `--fix` replaces relative path with an empty string

### ISSUE THREAD

**Issue by jacobchrismarsh** [qDanik/eslint-plugin-path#5]
In running this plugin, all of the relative paths would only be replaced with empty strings. 

I ran:
```bash
yarn eslint <file> --fix
```

I set up the plugin with the instructions in the README.

**Comment by qDanik** [comment]
Hi @jacobchrismarsh! Please provide me an example of your eslint & tsconfig files.

**Comment by mix0000** [comment]
Same

**Comment by qDanik** [comment]
@jacobchrismarsh @mix0000 Try latest release version ``1.2.2``
