### ISSUE TITLE
Problem with slashes

### ISSUE THREAD

**Issue by rinaldilucas** [qdanik/eslint-plugin-path#7]
I am trying to use this plugin on my project but the suggestion which I am getting has the inverted slash, as the image below:

![image](https://github.com/qdanik/eslint-plugin-path/assets/22507013/de349ebb-a115-4688-8941-8b5e423ba302)

**Comment by rinaldilucas** [comment]
I opened a pull request fixing this problem, but I don't know if it will break unix environment. If you could validate, that would be awesome. Also, thanks for your effort. Your plugin is awesome.

**Comment by qdanik** [comment]
@rinaldilucas thanks for the issue. Fix already merged into main branch and published to the npmjs registry. 
Please use latest version **1.2.3**!

**Comment by rinaldilucas** [comment]
You're awesome. Thanks!
